In [1]:
import numpy as np

## 数组拼接

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

# 以下三种方法都会返回一个新的数组
print(np.hstack((x,y)))
print(np.vstack((x,y)))
print(np.concatenate((x,y),axis=0)) # axis用于指定轴
print(np.concatenate((x,y),axis=1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


AxisError: axis 1 is out of bounds for array of dimension 1

可见,concateante函数不能将两个行向量拼接成一个矩阵,只能靠vstake函数完成此操作